/**
 * Codified Ability-protocol constants — the bytes-locked strings the model
 * sees in every spawn's prompt and in every pool's shared spine prefix.
 *
 * These five exports are the entire shape of the HDK 3.0 Ability protocol.
 * Every byte the model encounters in framework-controlled prompt content
 * traces back to one of these constants (or to grammar-sanitized
 * `ability.json` metadata interpolated through them).
 *
 * Lifted verbatim from production (`reasoning.run/src/prompts/playbooks.eta`,
 * `web-worker.eta`, `corpus-worker.eta`) with one substitution at the
 * noun position — see the Architectural reference section
 * for the rationale.
 *
 * **Do not duplicate these literals anywhere else.** `renderSpine` and
 * `renderAgentPreamble` reference these constants by name. Changing the
 * codified protocol is one edit here plus a trace-gate re-run; the
 * framework's internal call graph does not need touching.
 *
 * @packageDocumentation
 * @category Protocol
 */

/**
 * Boundary marker prepended to every per-spawn user-role message.
 *
 * Exact rendered shape: `Apply the **<name>** protocol.\n\n`
 * (marker line + blank line). The `<name>` comes from
 * `ability.manifest.protocol.name`, grammar-sanitized to
 * `[a-z][a-z0-9_-]{1,63}` at `defineAbility` time so it cannot break
 * the markdown bold or inject newlines.
 *
 * Framework-prepended by `renderAgentPreamble`. Ability `skill.eta` source
 * MUST NOT contain the literal `Apply the **` substring — `defineAbility`
 * rejects sources that do.
 */
export const BOUNDARY_MARKER = (name: string): string =>
  `Apply the **${name}** protocol.\n\n`;

/**
 * Framework intro paragraph emitted at the start of every spine.
 *
 * Verbatim from `reasoning.run/src/prompts/playbooks.eta:1`, with the noun
 * substituted (three occurrences inside the sentence). Followed at render
 * time by a blank line + `# Protocols` header + the per-ability catalog
 * entries.
 */
export const FRAMEWORK_INTRO =
  'You are an assistant working as part of a multi-agent workflow. ' +
  'You have access to the tools below, grouped by protocol. ' +
  'You should only use the tools for a given protocol when that particular ' +
  'protocol is requested explicitly in your task instructions.';

/**
 * Tool-selection rule emitted after all per-ability catalog entries.
 *
 * Verbatim from `reasoning.run/src/prompts/playbooks.eta:17-19` with the
 * noun substituted and the trailing `palette` → `tools` (palette was
 * retired from the framework vocabulary — see Architectural reference).
 * This is the abstract invariant the model routes against; concrete
 * cross-protocol BAD examples are NOT generated by the framework — the
 * abstract rule + dispatch-time auth-guard carry the discipline.
 */
export const TOOL_SELECTION_RULE =
  '# Tool selection rule\n\n' +
  'The agent system message will tell you which protocol to apply. ' +
  "Use only that protocol's tools. " +
  'The agent system message also carries an engineered PROCESS that dictates ' +
  'intra-protocol ordering. ' +
  "Follow that PROCESS, but constrained to the assigned protocol's tools.";

/**
 * Per-ability catalog entry shape emitted under the `# Protocols` header.
 *
 * Exact rendered shape (three lines + trailing blank line):
 * ```
 * ## <name>
 * Tools: <t1>, <t2>, ...
 * Use when: <useWhen>
 *
 * ```
 *
 * `name` is grammar-sanitized at `defineAbility` time. `tools` is the
 * `protocol.tools` array joined with `, `. `useWhen` is grammar-constrained
 * to a single sentence of printable characters with no chat-role markers,
 * no markdown code fences, no newlines.
 */
export const CATALOG_ENTRY = (
  name: string,
  tools: readonly string[],
  useWhen: string,
): string =>
  `## ${name}\nTools: ${tools.join(', ')}\nUse when: ${useWhen}\n`;

// ── Model fleet ───────────────────────────────────────────────────

/**
 * Model family entry in {@link VALIDATED_MODELS_3_0}.
 */
export interface ValidatedModelFamily {
  /** Model family identifier (e.g., `'qwen3'`, `'llama-3'`). */
  family: string;
  /**
   * Validated revisions of the family. `['*']` means all revisions of
   * the family pass; specific revision strings (e.g., `['3.5']`) restrict
   * to a subset.
   */
  revisions: readonly string[];
}

/**
 * Model families against which the HDK 3.0 Ability protocol has been
 * validated via production traces.
 *
 * Off-fleet models are unvalidated: the boundary marker, catalog format,
 * and tool-selection rule have not been verified to elicit correct
 * routing. Consumers running off-fleet models get best-effort routing —
 * the protocol may degrade silently. The framework does not gate on the
 * running model's family; HDK is model-agnostic by design.
 *
 * Extending the fleet for a new family requires re-running the
 * verification gates against that family and updating this
 * constant. `appProtocolVersion` does NOT bump for fleet expansion —
 * only for changes to the marker, catalog format, or tool-selection
 * rule that require re-validation across all listed families.
 */
export const VALIDATED_MODELS_3_0: readonly ValidatedModelFamily[] = [
  { family: 'qwen3', revisions: ['*'] },
  { family: 'qwen3.5', revisions: ['*'] },
  { family: 'llama-3', revisions: ['*'] },
  { family: 'phi-3.5', revisions: ['*'] },
  { family: 'gemma-3', revisions: ['*'] },
];

/**
 * The Ability protocol version this build of `@lloyal-labs/rig` ships.
 *
 * Abilities declare `appProtocolVersion` in `ability.json`; `defineAbility` and
 * `registry.enable` refuse to enable abilities whose declared version is not in
 * {@link SUPPORTED_ABILITY_PROTOCOL_VERSIONS}.
 */
export const ABILITY_PROTOCOL_VERSION = '3.0';

/**
 * The set of Ability protocol versions this build of `@lloyal-labs/rig`
 * accepts at ability-registration time. Within rig 3.x the only valid value
 * is `'3.0'`. A 4.0 protocol would require re-validation across every
 * family in {@link VALIDATED_MODELS_3_0}. Framework semver (rig 3.0 →
 * 3.1) does NOT bump the Ability protocol; that's the point of the separate
 * version line.
 */
export const SUPPORTED_ABILITY_PROTOCOL_VERSIONS: readonly string[] = ['3.0'];

/**
 * The property name the planner emits to route a task, and the only token in
 * this file the model both READS and WRITES.
 *
 * It is a constant rather than a literal because its value is an open question
 * that only an eval can close. The planner's grammar constrains this property
 * to an enum of `manifest.protocol.name` values, and the harness looks the
 * result up in a protocol-keyed map — so the key has never named what it holds:
 *
 * - `'app'`      the historical value. Carries a strong unrelated prior
 *                (mobile/web application) that the model must suppress on every
 *                planning call.
 * - `'ability'`  matches the distributable's name and sits in the agentic
 *                tool-use cluster, but still asks the model to map "ability"
 *                onto entries the spine labelled protocols.
 * - `'protocol'` names the `# Protocols` section the value is copied from, so
 *                the key and the spine heading agree. Consistent with Protocol
 *                already being the primitive for "when and how it participates".
 *
 * Changing it changes the tokens the model emits and the decode grammar, so it
 * is a behaviour change, not a refactor, and a regression here is SILENT —
 * tasks route to the wrong ability rather than erroring.
 *
 * Whatever this is set to, the planner prompt must name the SAME word: it is
 * passed to the plan template as `routingKey` for exactly that reason. Rule 6
 * of `plan.eta` historically said "source" in prose while the key said `app`
 * and the value was a protocol name — three nouns for one thing, in one
 * sentence. Keep them in agreement.
 */
export const TASK_ROUTING_KEY = 'ability';

// ── Distribution channel ─────────────────────────────────

/**
 * Canonical channel endpoint — `apps.lloyal.ai/v1/catalog.json`.
 * Framework-vendored compile-time constant; the harness cannot override.
 *
 * The `lloyal install` CLI uses {@link resolveAbilityEntry} to look up
 * a name + semver range against this catalog, verifies the catalog's
 * Ed25519 signature against the vendored trust roots, then fetches +
 * verifies the resolved manifest and tarball bytes before shelling out
 * to `npm install <tarballUrl>`. The CLI never supplies a URL.
 *
 * To use a different channel, fork `@lloyal-labs/channel-verify`, edit the
 * constant there, and republish both it and rig under different names. The
 * fork is a maintained source divergence; abilities signed by the canonical trust
 * roots will not load in the fork, and abilities signed by the fork's trust roots
 * will not load in unmodified upstream rig.
 *
 * Defined in `@lloyal-labs/channel-verify` and re-exported here, so rig's
 * public surface is unchanged and there is exactly one copy.
 */
export { CHANNEL_CATALOG_URL } from '@lloyal-labs/channel-verify';

/**
 * Framework-vendored trust roots — map from `publisherKeyId` (e.g.,
 * `'lloyal-platform-2026-q2'`) to the corresponding Ed25519 raw public key
 * bytes (32 bytes). The harness does NOT configure trust roots;
 * {@link verifyBundle} consumers (notably the install CLI) read this
 * constant directly.
 *
 * Multi-entry from day 1 to support key rotation: a new key is added in a
 * minor release while the previous key remains valid for N quarters, then is
 * removed in a future major. Abilities signed during the overlap window verify
 * under either key.
 *
 * The key bytes now live in `@lloyal-labs/channel-verify` and are re-exported
 * here. That package is the ONE copy: they were previously duplicated verbatim
 * between here and the CLI, while the rotation runbook named only this file —
 * so a rotation performed to the letter would have left the CLI unable to
 * verify the rotated catalog. Rotate in channel-verify and both follow.
 *
 * To use a different set, fork `@lloyal-labs/channel-verify`, edit the
 * constant there, and republish under a different name.
 */
export { CHANNEL_TRUST_ROOTS } from '@lloyal-labs/channel-verify';
