/**
 * Codified App-protocol constants — the bytes-locked strings the model
 * sees in every spawn's prompt and in every pool's shared spine prefix.
 *
 * These five exports are the entire shape of the HDK 3.0 App protocol.
 * Every byte the model encounters in framework-controlled prompt content
 * traces back to one of these constants (or to grammar-sanitized
 * `app.json` metadata interpolated through them).
 *
 * Lifted verbatim from production (`reasoning.run/src/prompts/playbooks.eta`,
 * `web-worker.eta`, `corpus-worker.eta`) with one substitution at the
 * noun position — see the Architectural reference section
 * for the rationale.
 *
 * **Do not duplicate these literals anywhere else.** `renderSpine` and
 * `renderAgentPreamble` reference these constants by name. Changing the
 * codified protocol is one edit here plus a trace-gate re-run; the
 * framework's internal call graph does not need touching.
 *
 * @packageDocumentation
 * @category Protocol
 */

/**
 * Boundary marker prepended to every per-spawn user-role message.
 *
 * Exact rendered shape: `Apply the **<name>** protocol.\n\n`
 * (marker line + blank line). The `<name>` comes from
 * `app.manifest.protocol.name`, grammar-sanitized to
 * `[a-z][a-z0-9_-]{1,63}` at `defineApp` time so it cannot break
 * the markdown bold or inject newlines.
 *
 * Framework-prepended by `renderAgentPreamble`. App `skill.eta` source
 * MUST NOT contain the literal `Apply the **` substring — `defineApp`
 * rejects sources that do.
 */
export const BOUNDARY_MARKER = (name: string): string =>
  `Apply the **${name}** protocol.\n\n`;

/**
 * Framework intro paragraph emitted at the start of every spine.
 *
 * Verbatim from `reasoning.run/src/prompts/playbooks.eta:1`, with the noun
 * substituted (three occurrences inside the sentence). Followed at render
 * time by a blank line + `# Protocols` header + the per-app catalog
 * entries.
 */
export const FRAMEWORK_INTRO =
  'You are an assistant working as part of a multi-agent workflow. ' +
  'You have access to the tools below, grouped by protocol. ' +
  'You should only use the tools for a given protocol when that particular ' +
  'protocol is requested explicitly in your task instructions.';

/**
 * Tool-selection rule emitted after all per-app catalog entries.
 *
 * Verbatim from `reasoning.run/src/prompts/playbooks.eta:17-19` with the
 * noun substituted and the trailing `palette` → `tools` (palette was
 * retired from the framework vocabulary — see Architectural reference).
 * This is the abstract invariant the model routes against; concrete
 * cross-protocol BAD examples are NOT generated by the framework — the
 * abstract rule + dispatch-time auth-guard carry the discipline.
 */
export const TOOL_SELECTION_RULE =
  '# Tool selection rule\n\n' +
  'The agent system message will tell you which protocol to apply. ' +
  "Use only that protocol's tools. " +
  'The agent system message also carries an engineered PROCESS that dictates ' +
  'intra-protocol ordering. ' +
  "Follow that PROCESS, but constrained to the assigned protocol's tools.";

/**
 * Per-app catalog entry shape emitted under the `# Protocols` header.
 *
 * Exact rendered shape (three lines + trailing blank line):
 * ```
 * ## <name>
 * Tools: <t1>, <t2>, ...
 * Use when: <useWhen>
 *
 * ```
 *
 * `name` is grammar-sanitized at `defineApp` time. `tools` is the
 * `protocol.tools` array joined with `, `. `useWhen` is grammar-constrained
 * to a single sentence of printable characters with no chat-role markers,
 * no markdown code fences, no newlines.
 */
export const CATALOG_ENTRY = (
  name: string,
  tools: readonly string[],
  useWhen: string,
): string =>
  `## ${name}\nTools: ${tools.join(', ')}\nUse when: ${useWhen}\n`;

// ── Model fleet ───────────────────────────────────────────────────

/**
 * Model family entry in {@link VALIDATED_MODELS_3_0}.
 */
export interface ValidatedModelFamily {
  /** Model family identifier (e.g., `'qwen3'`, `'llama-3'`). */
  family: string;
  /**
   * Validated revisions of the family. `['*']` means all revisions of
   * the family pass; specific revision strings (e.g., `['3.5']`) restrict
   * to a subset.
   */
  revisions: readonly string[];
}

/**
 * Model families against which the HDK 3.0 App protocol has been
 * validated via production traces.
 *
 * Off-fleet models are unvalidated: the boundary marker, catalog format,
 * and tool-selection rule have not been verified to elicit correct
 * routing. Consumers running off-fleet models get best-effort routing —
 * the protocol may degrade silently. The framework does not gate on the
 * running model's family; HDK is model-agnostic by design.
 *
 * Extending the fleet for a new family requires re-running the
 * verification gates against that family and updating this
 * constant. `appProtocolVersion` does NOT bump for fleet expansion —
 * only for changes to the marker, catalog format, or tool-selection
 * rule that require re-validation across all listed families.
 */
export const VALIDATED_MODELS_3_0: readonly ValidatedModelFamily[] = [
  { family: 'qwen3', revisions: ['*'] },
  { family: 'qwen3.5', revisions: ['*'] },
  { family: 'llama-3', revisions: ['*'] },
  { family: 'phi-3.5', revisions: ['*'] },
  { family: 'gemma-3', revisions: ['*'] },
];

/**
 * The App protocol version this build of `@lloyal-labs/rig` ships.
 *
 * Apps declare `appProtocolVersion` in `app.json`; `defineApp` and
 * `registry.enable` refuse to enable apps whose declared version is not in
 * {@link SUPPORTED_APP_PROTOCOL_VERSIONS}.
 */
export const APP_PROTOCOL_VERSION = '3.0';

/**
 * The set of App protocol versions this build of `@lloyal-labs/rig`
 * accepts at app-registration time. Within rig 3.x the only valid value
 * is `'3.0'`. A 4.0 protocol would require re-validation across every
 * family in {@link VALIDATED_MODELS_3_0}. Framework semver (rig 3.0 →
 * 3.1) does NOT bump the App protocol; that's the point of the separate
 * version line.
 */
export const SUPPORTED_APP_PROTOCOL_VERSIONS: readonly string[] = ['3.0'];

// ── Distribution channel ─────────────────────────────────

/**
 * Canonical channel endpoint — `apps.lloyal.ai/v1/catalog.json`.
 * Framework-vendored compile-time constant; the harness cannot override.
 *
 * The `harness.dev install` CLI uses {@link resolveAppEntry} to look up
 * a name + semver range against this catalog, verifies the catalog's
 * Ed25519 signature against {@link CHANNEL_TRUST_ROOTS}, then fetches +
 * verifies the resolved manifest and tarball bytes before shelling out
 * to `npm install <tarballUrl>`. The CLI never supplies a URL.
 *
 * To use a different channel, fork `@lloyal-labs/rig`, edit this constant
 * (and {@link CHANNEL_TRUST_ROOTS}), and republish under a different name.
 * The fork is a maintained source divergence; apps signed by the canonical
 * trust roots will not load in the fork, and apps signed by the fork's
 * trust roots will not load in unmodified upstream rig.
 */
export const CHANNEL_CATALOG_URL =
  'https://apps.lloyal.ai/v1/catalog.json';

/**
 * Canonical channel's `lloyal-platform-2026-q2` Ed25519 public key
 * (raw 32 bytes). Used to verify the apps.lloyal.ai catalog signature
 * and, transitively (via cross-checked `publisherKeyId`), bundle
 * signatures from lloyal-internal publishers.
 *
 * Generation: 2026-06-03, Node webcrypto Ed25519, private half stored
 * offline (1Password).
 * SHA-256 fingerprint: 9e0df3d25b8968a8b2ae9b86cb17a6922368c7cff9674a84b4a2527dd6457ec1
 * Base64: bUz2SCkISzbzD4/WftUw4Nou2bJixs6OYh/5lomQylI=
 *
 * Tests override {@link CHANNEL_TRUST_ROOTS} via `setTestTrustRoot()` in
 * `bundle.ts`, so this constant is inert under `NODE_ENV=test`.
 *
 * @internal
 */
const LLOYAL_PLATFORM_KEY_2026_Q2: Uint8Array = new Uint8Array([
  109, 76, 246, 72, 41, 8, 75, 54, 243, 15, 143, 214, 126, 213, 48, 224,
  218, 46, 217, 178, 98, 198, 206, 142, 98, 31, 249, 150, 137, 144, 202, 82,
]);

/**
 * Framework-vendored trust roots — map from `publisherKeyId` (e.g.,
 * `'lloyal-platform-2026-q2'`) to the corresponding Ed25519 raw public key
 * bytes (32 bytes). The harness does NOT configure trust roots;
 * {@link verifyBundle} consumers (notably the `harness.dev install` CLI)
 * read this constant directly.
 *
 * Multi-entry from day 1 to support key rotation: a new key is added in a
 * rig minor release while the previous key remains valid for N quarters,
 * then is removed in a future major. Apps signed during the overlap window
 * verify under either key.
 *
 * To use a different set, fork `@lloyal-labs/rig`, edit this constant (and
 * {@link CHANNEL_CATALOG_URL}), and republish under a different name.
 */
export const CHANNEL_TRUST_ROOTS: ReadonlyMap<string, Uint8Array> = Object.freeze(
  new Map<string, Uint8Array>([
    ['lloyal-platform-2026-q2', LLOYAL_PLATFORM_KEY_2026_Q2],
  ]),
);
